theme = "onedark"

[editor]
line-number = "relative"
cursorcolumn = true
cursorline = true
true-color = true
mouse = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false
